development:
  adapter: postgresql
  username: postgres
  min_messages: WARNING
  database: weather_blitz_development

test:
  adapter: postgresql
  username: postgres
  min_messages: WARNING
  database: weather_blitz_test