common: &common
  adapter: postgresql
  username: postgres
  min_messages: WARNING

development:
  <<: *common
  database: weather_blitz_development

test:
  <<: *common
  database: weather_blitz_test